include_guard()

if (AK_OS_RINOS)
    if (NOT DEFINED RINOS_FFMPEG_ROOT OR RINOS_FFMPEG_ROOT STREQUAL "")
        message(FATAL_ERROR "RINOS_FFMPEG_ROOT must point to the installed RinOS FFmpeg prefix")
    endif()

    set(_rinos_ffmpeg_include "${RINOS_FFMPEG_ROOT}/include")
    foreach(_library avutil avcodec avformat swresample)
        set(_archive "${RINOS_FFMPEG_ROOT}/lib/lib${_library}.a")
        if (NOT EXISTS "${_archive}")
            message(FATAL_ERROR "RinOS FFmpeg archive is missing: ${_archive}")
        endif()
        if (NOT TARGET FFmpeg::${_library})
            add_library(FFmpeg::${_library} STATIC IMPORTED GLOBAL)
            set_target_properties(FFmpeg::${_library} PROPERTIES
                IMPORTED_LOCATION "${_archive}"
                INTERFACE_INCLUDE_DIRECTORIES "${_rinos_ffmpeg_include}"
            )
        endif()
    endforeach()
    set_property(TARGET FFmpeg::avcodec PROPERTY INTERFACE_LINK_LIBRARIES FFmpeg::avutil)
    set_property(TARGET FFmpeg::avformat PROPERTY INTERFACE_LINK_LIBRARIES "FFmpeg::avcodec;FFmpeg::avutil")
    set_property(TARGET FFmpeg::swresample PROPERTY INTERFACE_LINK_LIBRARIES FFmpeg::avutil)
    message(STATUS "RinOS FFmpeg enabled from ${RINOS_FFMPEG_ROOT}")
elseif (NOT ANDROID)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(AVCODEC REQUIRED IMPORTED_TARGET libavcodec)
    pkg_check_modules(AVFORMAT REQUIRED IMPORTED_TARGET libavformat)
    pkg_check_modules(AVUTIL REQUIRED IMPORTED_TARGET libavutil)
    pkg_check_modules(LIBSWRESAMPLE REQUIRED IMPORTED_TARGET libswresample)
else()
    find_package(FFMPEG REQUIRED)
endif()
