#import <CredentialManagement/AuthenticatorAssertionResponse.idl>
#import <CredentialManagement/AuthenticatorAttestationResponse.idl>
#import <CredentialManagement/Credential.idl>

typedef DOMString PublicKeyCredentialType;
typedef long COSEAlgorithmIdentifier;

dictionary PublicKeyCredentialRpEntity {
    required DOMString name;
    DOMString id;
};

dictionary PublicKeyCredentialUserEntity {
    required BufferSource id;
    required DOMString name;
    required DOMString displayName;
};

dictionary PublicKeyCredentialParameters {
    required PublicKeyCredentialType type;
    required COSEAlgorithmIdentifier alg;
};

dictionary PublicKeyCredentialDescriptor {
    required PublicKeyCredentialType type;
    required BufferSource id;
    sequence<AuthenticatorTransport> transports;
};

enum AuthenticatorAttachment {
    "platform",
    "cross-platform"
};

enum ResidentKeyRequirement {
    "discouraged",
    "preferred",
    "required"
};

enum UserVerificationRequirement {
    "required",
    "preferred",
    "discouraged"
};

dictionary AuthenticatorSelectionCriteria {
    AuthenticatorAttachment authenticatorAttachment;
    ResidentKeyRequirement residentKey = "discouraged";
    boolean requireResidentKey = false;
    UserVerificationRequirement userVerification = "preferred";
};

enum AttestationConveyancePreference {
    "none",
    "indirect",
    "direct",
    "enterprise"
};

dictionary PublicKeyCredentialCreationOptions {
    required PublicKeyCredentialRpEntity rp;
    required PublicKeyCredentialUserEntity user;
    required BufferSource challenge;
    required sequence<PublicKeyCredentialParameters> pubKeyCredParams;
    unsigned long timeout;
    sequence<PublicKeyCredentialDescriptor> excludeCredentials = [];
    AuthenticatorSelectionCriteria authenticatorSelection;
    AttestationConveyancePreference attestation = "none";
    sequence<DOMString> hints = [];
};

dictionary PublicKeyCredentialRequestOptions {
    required BufferSource challenge;
    unsigned long timeout;
    USVString rpId;
    sequence<PublicKeyCredentialDescriptor> allowCredentials = [];
    UserVerificationRequirement userVerification = "preferred";
    sequence<DOMString> hints = [];
};

dictionary AuthenticationExtensionsClientOutputs {
};

[Exposed=Window, SecureContext]
interface PublicKeyCredential : Credential {
    readonly attribute ArrayBuffer rawId;
    readonly attribute AuthenticatorResponse response;
    readonly attribute DOMString? authenticatorAttachment;
    AuthenticationExtensionsClientOutputs getClientExtensionResults();
    static Promise<boolean> isUserVerifyingPlatformAuthenticatorAvailable();
    static Promise<boolean> isConditionalMediationAvailable();
};

partial dictionary CredentialCreationOptions {
    PublicKeyCredentialCreationOptions publicKey;
};

partial dictionary CredentialRequestOptions {
    PublicKeyCredentialRequestOptions publicKey;
};
